# Shadow Baoding config: tac_recon

agent:
  rollouts: 64
  learning_epochs: 8
  mini_batches: 32
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 3.61e-04
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  value_loss_scale: 1.0
  entropy_loss_scale: 0
  kl_threshold: 0

ssl_task:
  type: reconstruction
  n_rollouts: 1
  tactile_only: true
  loss_weight: 0.2707
  learning_rate: 1.0e-05

experiment:
  experiment_name: tac_recon
  wandb: 1
  wandb_kwargs:
    group: tac_recon
    name: '1'
