# Shadow Baoding config: tac_dynamics

agent:
  rollouts: 32
  learning_epochs: 4
  mini_batches: 16
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 2.08e-05
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  value_loss_scale: 1.0
  entropy_loss_scale: 0.05
  kl_threshold: 0

ssl_task:
  type: forward_dynamics
  n_rollouts: 1
  tactile_only: true
  loss_weight: 0.04839
  learning_rate: 1.53e-04
  seq_length: 4

experiment:
  experiment_name: tactile_dynamics
  wandb: 1
  wandb_kwargs:
    group: tactile_dynamics
    name: '1'
