# Shadow Baoding config: default

seed: 42

encoder:
  method: early
  hiddens:
  - 512
  - 256
  activations:
  - elu
  - elu
  layernorm: true
  state_preprocessor: True

policy:
  clip_log_std: true
  initial_log_std: 0
  min_log_std: -20.0
  max_log_std: 2.0
  hiddens:
  - 128
  - 64
  activations:
  - elu
  - elu
  - identity

value:
  hiddens:
  - 128
  - 64
  activations:
  - elu
  - elu
  - identity

experiment:
  directory: allegro_baoding
  debug: 0
  upload_videos: 0
  save_checkpoints: 1
  tb_log: true
  wandb: 1
  wandb_kwargs:
    project: roto_baoding
    entity: my-phd

trainer:
  num_eval_envs: 100
  max_global_timesteps_M: 250

sweeper:
  storage: sqlite:///roto_baoding.db
  warmup_timesteps_M: 100
  max_sweep_timesteps_M: 150
