# Franka Find config: full_recon

agent:
  rollouts: 64
  learning_epochs: 4
  mini_batches: 64
  discount_factor: 0.99
  lambda: 0.95
  value_clip: 0.2
  ratio_clip: 0.2
  kl_threshold: 0
  learning_rate: 7.39e-05
  entropy_loss_scale: 0
  value_loss_scale: 1.0
  grad_norm_clip: 1.0

ssl_task:
  type: reconstruction
  n_rollouts: 1
  tactile_only: false
  loss_weight: 0.0023
  learning_rate: 5.91e-05
  learning_epochs_ratio: 1

experiment:
  experiment_name: full_recon
  save_checkpoints: 1
  tb_log: 1
  wandb: 1
  wandb_kwargs:
    group: full_recon
    name: '1'
