# Franka Find config: rl_only_ptg
observations:
  obs_list:
  - prop
  - depth
  - tactile
  obs_stack: 3
  tactile_cfg:
    binary_tactile: true
    binary_threshold: 0.0
  pixel_cfg:
    width: 80
    height: 80
    latent_pixel_dim: 256
    normalise_rgb: false
    max_depth: 2.0

agent:
  rollouts: 32
  learning_epochs: 4
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.95
  value_clip: 0.2
  ratio_clip: 0.2
  kl_threshold: 0
  learning_rate: 1.0e-05
  entropy_loss_scale: 0.01
  value_loss_scale: 0.5
  grad_norm_clip: 1.0

experiment:
  experiment_name: rl_only_ptd
  save_checkpoints: 1
  tb_log: 1
  wandb: 1
  wandb_kwargs:
    group: rl_only_ptd
    name: new hparam

trainer:
  num_eval_envs: 20
  max_global_timesteps_M: 400


sweeper:
  storage: sqlite:///franka_find_pixels.db
  warmup_timesteps_M: 15
  max_sweep_timesteps_M: 25