asset_path: /home/elle/code/debug/roto/roto/assets/orca/orcahand_right.urdf
usd_dir: /home/elle/code/debug/roto/roto/assets/orca
usd_file_name: orcahand_right.usd
force_usd_conversion: false
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 0.0
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive: null
collider_type: convex_hull
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props: null
collision_props: null
activate_contact_sensors: true
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: false
  solver_position_iteration_count: 32
  solver_velocity_iteration_count: 16
  sleep_threshold: 0.0
  stabilization_threshold: null
  fix_root_link: null
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2026-03-09 at 16:04:37.
##
